name: Django from mash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7,]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: install flake8
      run: |
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
    - name: Test with flake8
      run: |
        # запуск проверки проекта по flake8
        python -m flake8 
    - name: Django tests
      run: |
        python infra_project/infra_app/tests.py